// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class UserProfile;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Commands

typedef GPB_ENUM(Commands) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Commands_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Commands_Request = 0,
  Commands_Reply = 1,
  Commands_Update = 2,
};

GPBEnumDescriptor *Commands_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Commands_IsValidValue(int32_t value);

#pragma mark - TestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TestRoot : GPBRootObject
@end

#pragma mark - GetUser

typedef GPB_ENUM(GetUser_FieldNumber) {
  GetUser_FieldNumber_Command = 1,
  GetUser_FieldNumber_Openid = 3,
};

@interface GetUser : GPBMessage

@property(nonatomic, readwrite) Commands command;

@property(nonatomic, readwrite, copy, null_resettable) NSString *openid;

@end

/**
 * Fetches the raw value of a @c GetUser's @c command property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetUser_Command_RawValue(GetUser *message);
/**
 * Sets the raw value of an @c GetUser's @c command property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetUser_Command_RawValue(GetUser *message, int32_t value);

#pragma mark - UserProfile

typedef GPB_ENUM(UserProfile_FieldNumber) {
  UserProfile_FieldNumber_Command = 1,
  UserProfile_FieldNumber_Uid = 2,
  UserProfile_FieldNumber_Openid = 3,
  UserProfile_FieldNumber_Status = 5,
  UserProfile_FieldNumber_Nickname = 18,
  UserProfile_FieldNumber_RefreshAt = 19,
  UserProfile_FieldNumber_FriendsArray = 20,
};

@interface UserProfile : GPBMessage

@property(nonatomic, readwrite) Commands command;

@property(nonatomic, readwrite, copy, null_resettable) NSString *nickname;

@property(nonatomic, readwrite) int32_t uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *openid;

@property(nonatomic, readwrite) int32_t status;

@property(nonatomic, readwrite) float refreshAt;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UserProfile*> *friendsArray;
/** The number of items in @c friendsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger friendsArray_Count;

@end

/**
 * Fetches the raw value of a @c UserProfile's @c command property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UserProfile_Command_RawValue(UserProfile *message);
/**
 * Sets the raw value of an @c UserProfile's @c command property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUserProfile_Command_RawValue(UserProfile *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
